In [1]:
"""
ECGR 5105 - Intro to Machine Learning
Torch Learning Grounds. Not a homework Submission File
Phillip Harmon
""";


In [2]:
import numpy as np
import matplotlib as plt
import pandas as pd
import torch


In [3]:
#Define the model
def model(x, w):
    return w[2] * x * x + w[1] * x + w[0]


In [4]:
#Define the loss function
def cost(y_p, y):
    square_error = (y_p - y)**2
    return square_error.mean()


In [5]:
#Define Forward Pass Function
def forward_pass(x, y, params, enable_grad):
    with torch.set_grad_enabled(enable_grad):
        loss = cost( model(x, params) , y)
    return loss

In [6]:
"""
Custom Gradient Descent
No Scaling or Validation
"""

#Define the Training Loop
def train_loop(epochs, learn_rate, params, x, y):
    for epoch in range(1, epochs + 1):
        if params.grad is not None:
            params.grad.zero_()
        
        y_p = model(x, params)
        loss = cost(y_p, y)
        loss.backward()
        
        with torch.no_grad():
            params -= learn_rate * params.grad
            
        if epoch% 500 == 0:
            print('Epoch {}, Loss {}'.format(epoch, loss))

    return params

#Input Dataset Definition

#measurement
x = torch.tensor([35.7, 55.9, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4, 60.4, 68.4])
#celcius
y = torch.tensor([0.5, 14.0, 15.0, 28.0, 11.0, 8.0, 3.0, -4.0, 6.0, 13.0, 21.0])
#Cleaning the inputs
x = (x - x.min()) / (x.max() - x.min())
y = (y - y.min()) / (y.max() - y.min())

#Define Constructs
epochs = 5000
learn_rate = 1e-2
params = torch.tensor([1.0, 1.0, 0.0], requires_grad=True)
optimizer = torch.optim.SGD([params], lr=learn_rate)

#Perform the training

train_loop(
    epochs = epochs,
    learn_rate = learn_rate,
    params = params,
    x = x,
    y = y)


Epoch 500, Loss 0.00670528132468462
Epoch 1000, Loss 0.0028758146800100803
Epoch 1500, Loss 0.0023862847592681646
Epoch 2000, Loss 0.0023079682141542435
Epoch 2500, Loss 0.0022814751137048006
Epoch 3000, Loss 0.002262611174955964
Epoch 3500, Loss 0.002245859242975712
Epoch 4000, Loss 0.0022304588928818703
Epoch 4500, Loss 0.0022162289824336767
Epoch 5000, Loss 0.002203074051067233


tensor([-0.0247,  0.8415,  0.1799], requires_grad=True)

In [7]:
"""
SGD Optimizer
No Scaling or Validation
"""

#Define the Training Loop
def train_loop(epochs, optimizer, params, x, y):
    for epoch in range(1, epochs + 1):
        y_p = model(x, params)
        loss = cost(y_p, y)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
            
        if epoch% 500 == 0:
            print('Epoch {}, Loss {}'.format(epoch, loss))

    return params

#Input Dataset Definition

#measurement
x = torch.tensor([35.7, 55.9, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4, 60.4, 68.4])
#celcius
y = torch.tensor([0.5, 14.0, 15.0, 28.0, 11.0, 8.0, 3.0, -4.0, 6.0, 13.0, 21.0])
#Cleaning the inputs
x = (x - x.min()) / (x.max() - x.min())
y = (y - y.min()) / (y.max() - y.min())

#Define Constructs
epochs = 5000
learn_rate = 1e-2
params = torch.tensor([1.0, 1.0, 0.0], requires_grad=True)
optimizer = torch.optim.SGD([params], lr=learn_rate)

#Perform the training

train_loop(
    epochs = epochs,
    optimizer = optimizer,
    params = params,
    x = x,
    y = y)


Epoch 500, Loss 0.00670528132468462
Epoch 1000, Loss 0.0028758146800100803
Epoch 1500, Loss 0.0023862847592681646
Epoch 2000, Loss 0.0023079682141542435
Epoch 2500, Loss 0.0022814751137048006
Epoch 3000, Loss 0.002262611174955964
Epoch 3500, Loss 0.002245859242975712
Epoch 4000, Loss 0.0022304588928818703
Epoch 4500, Loss 0.0022162289824336767
Epoch 5000, Loss 0.002203074051067233


tensor([-0.0247,  0.8415,  0.1799], requires_grad=True)

In [8]:
"""
Adam Optimizer
No Scaling or Validation
"""

#Define the Training Loop
def train_loop(epochs, optimizer, params, x, y):
    for epoch in range(1, epochs + 1):
        y_p = model(x, params)
        loss = cost(y_p, y)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
            
        if epoch% 500 == 0:
            print('Epoch {}, Loss {}'.format(epoch, loss))

    return params

#Input Dataset Definition

#measurement
x = torch.tensor([35.7, 55.9, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4, 60.4, 68.4])
#celcius
y = torch.tensor([0.5, 14.0, 15.0, 28.0, 11.0, 8.0, 3.0, -4.0, 6.0, 13.0, 21.0])
#Cleaning the inputs
x = (x - x.min()) / (x.max() - x.min())
y = (y - y.min()) / (y.max() - y.min())

#Define Constructs
epochs = 5000
learn_rate = 1e-2
params = torch.tensor([1.0, 1.0, 0.0], requires_grad=True)
optimizer = torch.optim.Adam([params], lr=learn_rate)

#Perform the training

train_loop(
    epochs = epochs,
    optimizer = optimizer,
    params = params,
    x = x,
    y = y)


Epoch 500, Loss 0.002141732955351472
Epoch 1000, Loss 0.0020466074347496033
Epoch 1500, Loss 0.0020434700418263674
Epoch 2000, Loss 0.0020421408116817474
Epoch 2500, Loss 0.0020417815539985895
Epoch 3000, Loss 0.0020417245104908943
Epoch 3500, Loss 0.0020417196210473776
Epoch 4000, Loss 0.0020417184568941593
Epoch 4500, Loss 0.0020417189225554466
Epoch 5000, Loss 0.0020417189225554466


tensor([0.0029, 0.6968, 0.3195], requires_grad=True)

In [9]:
"""
Adam Optimizer
T/V Split
No Scaling
"""

#Define the Training Loop
def train_loop(epochs, optimizer, params, x_t, y_t, x_v, y_v):
    for epoch in range(1, epochs + 1):
        loss_t = forward_pass(
            x = x_t,
            y = y_t,
            params = params,
            enable_grad = True)
        
        loss_v = forward_pass(
            x = x_v,
            y = y_v,
            params = params,
            enable_grad = False)
        
        if epoch <= 3 or epoch % 500 == 0:
            print('Epoch {} | Training Loss = {} | Validation Loss = {}'.format(epoch, loss_t, loss_v))
        
        optimizer.zero_grad()
        loss_t.backward()
        optimizer.step()

    return params

#Input Dataset Definition

#measurement
x = torch.tensor([35.7, 55.9, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4, 60.4, 68.4])
#celcius
y = torch.tensor([0.5, 14.0, 15.0, 28.0, 11.0, 8.0, 3.0, -4.0, 6.0, 13.0, 21.0])
#Cleaning the inputs
x = (x - x.min()) / (x.max() - x.min())
y = (y - y.min()) / (y.max() - y.min())

#Train/Test Split
split = int(0.2 * x.shape[0])
shuffle_index = torch.randperm(x.shape[0])
index_t = shuffle_index[:-split]
index_v = shuffle_index[-split:]
x_t = x[index_t]
y_t = y[index_t]
x_v = x[index_v]
y_v = y[index_v]

#Define Constructs
epochs = 5000
learn_rate = 1e-2
params = torch.tensor([1.0, 1.0, 0.0], requires_grad=True)
optimizer = torch.optim.Adam([params], lr=learn_rate)

#Perform the training

train_loop(
    epochs = epochs,
    optimizer = optimizer,
    params = params,
    x_t = x_t,
    y_t = y_t,
    x_v = x_v,
    y_v = y_v)


Epoch 1 | Training Loss = 1.0765001773834229 | Validation Loss = 1.1896332502365112
Epoch 2 | Training Loss = 1.0390621423721313 | Validation Loss = 1.1511130332946777
Epoch 3 | Training Loss = 1.002382755279541 | Validation Loss = 1.1132497787475586
Epoch 500 | Training Loss = 0.002299879677593708 | Validation Loss = 0.0015392601490020752
Epoch 1000 | Training Loss = 0.0022700007539242506 | Validation Loss = 0.0013620927929878235
Epoch 1500 | Training Loss = 0.0022695520892739296 | Validation Loss = 0.0013421372277662158
Epoch 2000 | Training Loss = 0.002269384451210499 | Validation Loss = 0.0013280060375109315
Epoch 2500 | Training Loss = 0.002269347198307514 | Validation Loss = 0.0013203400885686278
Epoch 3000 | Training Loss = 0.0022693423088639975 | Validation Loss = 0.0013172781327739358
Epoch 3500 | Training Loss = 0.0022693416103720665 | Validation Loss = 0.001316437846980989
Epoch 4000 | Training Loss = 0.002269341377541423 | Validation Loss = 0.0013162958202883601
Epoch 4500 

tensor([-0.0010,  0.7474,  0.2713], requires_grad=True)

In [10]:
(0.02620089240372181 - 0.011507327668368816) / 0.02620089240372181

0.5608039798394725